# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  defaults:
    remote: upstream

  self:
    path: helium_mapper

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: retfie
      url-base: https://github.com/retfie

  projects:
    - name: zephyr
      remote: upstream
      revision: main
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - segger
          - tinycrypt
          - loramac-node
          - mbedtls
    - name: mcuboot
      revision: main
      path: bootloader/mcuboot
    - name: zcbor
      revision: 0.6.0
      path: modules/lib/zcbor
